# Don't change this! Version used to track needed updates.
version = 1
catchRadius = 2.0
intrigueChance = 0.33
intrigueRadius = 3.5
netheriteFishingRod = true
fishDropNoLoot = true
allowFishingWithoutFish = false