name = "Affogato"
author = "pajic"
version = "Beta-29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46803d63d6fe3eaa3bd3bbfa4c4ed2dbbcd5e9c0c4271ff8adab1bb8f358b972"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
