name = "Affogato"
author = "pajic"
version = "Beta-24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af21d5e9db157bb804c4254c887316e859ce17f8a958786d0c9429366ed2cc8a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
