name = "Affogato"
author = "pajic"
version = "Beta-6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47befc7ea6e3c6024a39e1371363e2adb98010ebbad6d4093428c4b9aa028857"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
