name = "Affogato"
author = "pajic"
version = "Beta-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4111d2b046342580f831bd6d06bc8890f52204c1a724fcefd3bb4b320e972249"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
