name = "Affogato"
author = "pajic"
version = "Beta-31"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "854cc69909d86a5c1f6528301c5440421cb8221f8bf1155994fecdacbfdfe0fd"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
