name = "Affogato"
author = "pajic"
version = "Beta-9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebaffde218e43524613676c14831f007f1a8a5d311bb7cb4fbf05c9d72abe6eb"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
