name = "Affogato"
author = "pajic"
version = "Alpha-3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe9a6fb4500d1b6ec00486ce86ee0dce3989cb4e56ac1331f692d65138747bd5"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
