name = "Affogato"
author = "pajic"
version = "Beta-21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbe3874f12f7312907b408eff3175d297a91250a90238b7a5e63edfb230e0027"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
