name = "Affogato"
author = "pajic"
version = "Beta-27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04a59e8d57f4c420bbd67fa863b4508ca1fb820c75cdb8c5a6aecf1b0d041a0a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
