name = "Affogato"
author = "pajic"
version = "Beta-20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51e45cdc3ce0b3448fdda7acd3b5f4d8493a77bce60936159f4f9ac854225ea4"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
