name = "Affogato"
author = "pajic"
version = "Beta-1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad2f52b3ae0442e6d72902bfe39e0417c567d919692ef593fd4b71ba2ff75b27"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
