name = "Affogato"
author = "pajic"
version = "Beta-30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d24a96138ac64a3a759cce961e152c6643f4df6a44e96edd0fddf82ae8f075fe"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
