name = "Affogato"
author = "pajic"
version = "Beta-13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd112dd80fe2f40850c1bd439b8a3a6abdac1adda58c25c300e2ccf386c9786b"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
