name = "Affogato"
author = "pajic"
version = "Beta-3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83ead60318b96866c7c43424dcbc2536dae319267acc1f1682f28590d37262ba"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
