name = "Affogato"
author = "pajic"
version = "26.1.0-alpha.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "574d335c38f8383d49c030ded3ba64730e3fa05d25ac3fc131602c66a1930649"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1", "26.1.2"]
datapack-folder = "datapacks"
