name = "Affogato"
author = "pajic"
version = "1.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bef5682aeecd3716f9b33e34ea615fd5fbdced986110aae4a24c3619edcdc67"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
