name = "Affogato"
author = "pajic"
version = "Beta-7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "781a3aab8a3f334e24b63f6899a19228f57a8c59414afae96305f91369ea6164"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
