name = "Affogato"
author = "pajic"
version = "Beta-14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdf58e431cc27c159c2eb447919d4aae16311abd49aa7d676d03ad5b3725a8f6"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
