name = "Affogato"
author = "pajic"
version = "Alpha-3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "883c42ea108773809c16d05b56b7ba0117a43bb042f01088da49f7717290295f"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
