name = "Affogato"
author = "pajic"
version = "Beta-19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37b202d77e1c84ec293701830d954309a59dedb2f7fc0616adda3bcf290a011a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
