name = "Affogato"
author = "pajic"
version = "Beta-28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9881bbee4de08f52ac47a843df1f0db559e7be7d7acce58274bf448750ac4d96"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
