name = "Affogato"
author = "pajic"
version = "PreRelease-8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9eabe8c279c05df6a34bdfb2b7a3b0808a06ae9d88ebdb7a6f441dc0bc4bc23"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
