name = "Affogato"
author = "pajic"
version = "Beta-2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "466f87f5dd235cdc5f386c8a78a0aafe2355bc4aa13c358d8a3a4109a183ab1e"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
