name = "Affogato"
author = "pajic"
version = "Beta-30"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "053d67cd60279ad554dae849ee81bc742b2f2173d38035f45b8713ba3378571d"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
