name = "Affogato"
author = "pajic"
version = "Beta-3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27265e5530fdbb3dd2cbae926c74d062f57860336b6c9d166e9c22788c1a2584"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
