[betterDungeons.general]
enableHeads = true
removeVanillaDungeons = false
enableNetherBlocks = false
[betterDungeons.zombieDungeon]
zombieDungeonMaxSurfaceStaircaseLength = 20
[betterDungeons.smallDungeon]
bannerMaxCount = 2
chestMinCount = 1
chestMaxCount = 2
enableOreProps = true
[betterDungeons.smallNetherDungeon]
enabled = true
witherSkeletonsDropWitherSkulls = true
blazesDropBlazeRods = true
bannerMaxCount = 2
