# Don't change this! Version used to track needed updates.
version = 1
canOpenFromInventory = false
canOpenWithRightClick = false
canAttachToChestplate = false
canEquipInChestSlot = false
canStoreShulkers = false
preventUnequipWhenNotEmpty = true

[leatherSize]
rows = 1
columns = 7

[copperSize]
rows = 2
columns = 7

[ironSize]
rows = 3
columns = 7

[goldenSize]
rows = 4
columns = 7

[diamondSize]
rows = 5
columns = 7

[netheriteSize]
rows = 6
columns = 7