# Don't change this! Version used to track needed updates.
version = 1
lowerShield = true
raiseHotbarPixels = 2
perDimensionBrightness = [
    [ "minecraft:the_nether", 100 ],
    [ "minecraft:overworld", 25 ],
    [ "minecraft:the_end", 0 ]
]

[[shields]]
id = "minecraft:shield"
offset = -4.0

[[shields]]
id = "rearm:netherite_shield"
offset = -4.0