# Don't change this! Version used to track needed updates.
version = 1

[armorBars]
displayArmorBars = true
displayBarsForUndamagedArmor = true
yOffset = 0
useCustomBarColorForUndamagedArmor = true

[armorBars.customBarColorForUndamagedArmor]
# Red component, 0 to 255
r = 255
# Green component, 0 to 255
g = 255
# Blue component, 0 to 255
b = 255

[lowDurabilityWarning]
displayWarningForTools = false
displayWarningForArmor = false
onlyOnMendingItems = false
minDurabilityPointsBeforeWarning = 100
minDurabilityPercentageBeforeWarning = 10
blinkTime = 1.0