# Don't change this! Version used to track needed updates.
version = 1

[disabler]
disablerEnabled = true
disabledEnchantments = [
	"minecraft:mending",
	"minecraft:looting",
	"minecraft:fortune",
	"minecraft:infinity",
	"minecraft:unbreaking",
	"minecraft:thorns",
	"minecraft:bane_of_arthropods"
]

[maxLevel]
modifyMaxLevels = false
maxLevels = [  ]
limitObtainableEnchantmentLevel = false
obtainableEnchantmentLevels = [  ]

[trades]
limitBookTradeLevel = false
bookTradeLevelLimit = 5
modifyEnchantedBookTradeUses = false
maxEnchantedBookTradeUses = 12
modifyEnchantedItemTradeUses = false
maxEnchantedItemTradeUses = 3
enchantedBookTradeRestockEnabled = true
enchantedItemTradeRestockEnabled = true

[enchantingTable]
enchantingTableEnabled = true
modifyMaxTablePower = false
maxTablePower = 15
modifyLapisCost = false
lapisCostFormula = "i+1"
modifyXpCost = true
xpCostFormula = "(3*i)+4"

[loot]
modifyEnchantWithLevelsMaxPower = false
enchantWithLevelsMaxPower = 50